### ISSUE TITLE
Using a new Market Place smart contract address in frontend

### ISSUE THREAD

**Issue by Joon2000** [bnb-chain/greenfield-data-marketplace-frontend#25]
I'm in the process of deploying a Greenfield MarketPlace (https://docs.bnbchain.org/greenfield-docs/docs/tutorials/app/data-marketplace/overview/).

I followed the instructions at (https://github.com/bnb-chain/greenfield-data-marketplace-contracts) and deployed a new MarketPlace Smart Contract.

After that, I updated the environment file at (https://github.com/bnb-chain/greenfield-data-marketplace-frontend) with the address of the newly deployed smart contract.

However, I'm encountering a revert error. All I did was replace the existing MarketPlace smart contract address in the environment file with the address of my newly deployed marketplace smart contract.

I put my new address in environment file's  REACT_APP_MARKETPLACE_CONTRACT_ADDRESS

**Comment by CocoStarZ** [comment]
Could you pls share more details of the error and steps to reproduce it? Also you could share your repo link for us to check

**Comment by Joon2000** [comment]
@CocoStarZ 

First,
 I deployed a new contract following the steps of  (https://github.com/bnb-chain/greenfield-data-marketplace-contracts). I changed the (forge script ./script/1-deploy.s.sol --rpc-url ${RPC_LOCAL} --legacy --broadcast --private-key ${OP_PRIVATE_KEY}) command to (forge script ./script/1-deploy.s.sol --rpc-url ${RPC_TESTNET} --legacy --broadcast --private-key ${OP_PRIVATE_KEY})

The following is what i got in console after deploying the contract
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
---------------------------------------------------------------------------------------------------------------
{OP_PRIVATE_KEY}
[⠔] Compiling...
No files changed, compilation skipped
Script ran successfully.

== Logs ==
  operator balance: 0
  init owner: 0x5065Fd0b55a7eF076306b25Ef4aC7E34efDBBC2C
  deployer address: 0xa1Df5223D7e59421b9D78CE29c2AeA8334080ac8
  implMarketplace address: 0x87313A361b9e4f6C5e8e74B7E7ddf84c44176589
  proxyAdmin address: 0xC31a4632Ac6f09e26f5A953dD23678a3f9C8E0F5
  proxyMarketplace address: 0x902D457C48456433461a35Cf754dE13C8Ee6A16b
EIP-3855 is not supported in one or more of the RPCs used.
Unsupported Chain IDs: 97.
Contracts deployed with a Solidity version equal or higher than 0.8.20 might not work properly.
For more information, please see https://eips.ethereum.org/EIPS/eip-3855

## Setting up 1 EVM.

==========================

Chain 97

Estimated gas price: 5 gwei

Estimated total gas used for script: 9177089

Estimated amount required: 0.045885445 ETH

==========================

###
Finding wallets for all the necessary addresses...
##
Sending transactions [0 - 2].
⠙ [00:00:00] [######################################################################################################################################] 3/3 txes (0.0s)
Transactions saved to: /home/joonwon/bnb/greenfield-data-marketplace-contracts/broadcast/1-deploy.s.sol/97/run-latest.json

Sensitive values saved to: /home/joonwon/bnb/greenfield-data-marketplace-contracts/cache/1-deploy.s.sol/97/run-latest.json

##
Waiting for receipts.
⠚ [00:00:06] [##################################################################################################################################] 3/3 receipts (0.0s)
##### bsc-testnet
✅  [Success]Hash: 0x68529a670adeadee48e1a41abe31f74f71b902a87c91b992a5e4ff418fa98a0c
Contract Address: 0xa1Df5223D7e59421b9D78CE29c2AeA8334080ac8
Block: 38301491
Paid: 0.00857208 ETH (1714416 gas * 5 gwei)


##### bsc-testnet
✅  [Success]Hash: 0xa729c126ee0050239df0077d1e349d7c70e2809aac779ae1b94b5b982e2008b7
Contract Address: 0x87313A361b9e4f6C5e8e74B7E7ddf84c44176589
Block: 38301491
Paid: 0.02152568 ETH (4305136 gas * 5 gwei)


##### bsc-testnet
✅  [Success]Hash: 0x23e95df0014acd1381ad54dbea05aaf0b67f3697649d68cec4bb5b7459b52ff6
Block: 38301491
Paid: 0.00463039 ETH (926078 gas * 5 gwei)


Transactions saved to: /home/joonwon/bnb/greenfield-data-marketplace-contracts/broadcast/1-deploy.s.sol/97/run-latest.json

Sensitive values saved to: /home/joonwon/bnb/greenfield-data-marketplace-contracts/cache/1-deploy.s.sol/97/run-latest.json



==========================

ONCHAIN EXECUTION COMPLETE & SUCCESSFUL.
Total Paid: 0.03472815 ETH (6945630 gas * avg 5 gwei)

Transactions saved to: /home/joonwon/bnb/greenfield-data-marketplace-contracts/broadcast/1-deploy.s.sol/97/run-latest.json

Sensitive values saved to: /home/joonwon/bnb/greenfield-data-marketplace-contracts/cache/1-deploy.s.sol/97/run-latest.json
----------------------------------------------------------------------------------------------
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


Secondly, 
I entered the deployed address (0xa1Df5223D7e59421b9D78CE29c2AeA8334080ac8) from the first step into the environment file (.env.development.local) for the REACT_APP_MARKETPLACE_CONTRACT_ADDRESS variable at (https://github.com/bnb-chain/greenfield-data-marketplace-frontend). I didn't make any other changes. 
(Here's our repository: https://github.com/AIM-Intelligence/Ai-Binance-Cast-Market)

However, when I ran "npm start dev," I encountered an "execution reverted" error.
<img width="422" alt="image" src="https://github.com/bnb-chain/greenfield-data-marketplace-frontend/assets/103424415/7a27f71f-8c3b-4f65-b6a6-8c6feb1e427e">

**Comment by ruixinM** [comment]
@Joon2000 Hi, Joon2000, I cloned your git repo and got the same error after running it. I guess it may be that the datamarketplace contract you deployed has some exceptions. Can you provide the source code for the deployed 0xa1Df5223D7e59421b9D78CE29c2AeA8334080ac8

**Comment by Joon2000** [comment]
@ruixinM I just used the existing sample found at (https://github.com/bnb-chain/greenfield-data-marketplace-contracts) and didn't make any changes. So, the source code might be located here (https://github.com/bnb-chain/greenfield-data-marketplace-contracts/tree/master/contracts). The specific steps were described in my previous reply.

When I ignored the revert error and attempted to list my object (or bucket) on the market, I encountered a 'Could not estimate gas. There might be an error in the contract, and this transaction could fail.' error related to REACT_APP_MARKETPLACE_CONTRACT_ADDRESS. I also tried using the implMarketplace address (0x87313A361b9e4f6C5e8e74B7E7ddf84c44176589), which was mentioned in the 'Logs' section of my previous reply, but I faced the same gas error.

I'm uncertain about which address to assign to REACT_APP_MARKETPLACE_CONTRACT_ADDRESS from the following options: 
init owner: 0x5065Fd0b55a7eF076306b25Ef4aC7E34efDBBC2C
deployer address: 0xa1Df5223D7e59421b9D78CE29c2AeA8334080ac8
implMarketplace address: 0x87313A361b9e4f6C5e8e74B7E7ddf84c44176589
proxyAdmin address: 0xC31a4632Ac6f09e26f5A953dD23678a3f9C8E0F5
proxyMarketplace address: 0x902D457C48456433461a35Cf754dE13C8Ee6A16b

**Comment by ruixinM** [comment]
@Joon2000  Sorry, I missed your reply. Has the problem been resolved now? The address of REACTAPP-MARKETPLACE-CONTRACTADDRESS is the address after the marketplace.sol contract is deployed. You can try deploying marketplace.sol and then use its address.
